use {
    super::{set_coption, set_coption_some, COption, Initializable, Transmutable},
    core::{
        mem::{offset_of, MaybeUninit},
        ptr::addr_of_mut,
    },
    pinocchio::{
        account::{
            initialize_bytes_with_sized_self, AccountContent, Initializable as PInitializable,
        },
        program_error::ProgramError,
        pubkey::Pubkey,
    },
};

/// Internal representation of a mint data.
#[repr(C)]
pub struct Mint {
    /// Optional authority used to mint new tokens. The mint authority may only
    /// be provided during mint creation. If no mint authority is present
    /// then the mint has a fixed supply and no further tokens may be
    /// minted.
    mint_authority: COption<Pubkey>,

    /// Total supply of tokens.
    supply: [u8; 8],

    /// Number of base 10 digits to the right of the decimal place.
    pub decimals: u8,

    /// Is `true` if this structure has been initialized.
    is_initialized: u8,

    // Indicates whether the freeze authority is present or not.
    //freeze_authority_option: [u8; 4],
    /// Optional authority to freeze token accounts.
    freeze_authority: COption<Pubkey>,
}

impl Mint {
    #[inline(always)]
    pub fn set_supply(&mut self, supply: u64) {
        self.supply = supply.to_le_bytes();
    }

    #[inline(always)]
    pub fn supply(&self) -> u64 {
        u64::from_le_bytes(self.supply)
    }

    #[inline(always)]
    pub fn set_initialized(&mut self) {
        self.is_initialized = 1;
    }

    #[inline(always)]
    pub fn clear_mint_authority(&mut self) {
        self.mint_authority.0[0] = 0;
    }

    #[inline(always)]
    pub fn set_mint_authority(&mut self, mint_authority: &Pubkey) {
        self.mint_authority.0[0] = 1;
        self.mint_authority.1 = *mint_authority;
    }

    #[inline(always)]
    pub fn mint_authority(&self) -> Option<&Pubkey> {
        if self.mint_authority.0[0] == 1 {
            Some(&self.mint_authority.1)
        } else {
            None
        }
    }

    #[inline(always)]
    pub fn clear_freeze_authority(&mut self) {
        self.freeze_authority.0[0] = 0;
    }

    #[inline(always)]
    pub fn set_freeze_authority(&mut self, freeze_authority: &Pubkey) {
        self.freeze_authority.0[0] = 1;
        self.freeze_authority.1 = *freeze_authority;
    }

    #[inline(always)]
    pub fn freeze_authority(&self) -> Option<&Pubkey> {
        if self.freeze_authority.0[0] == 1 {
            Some(&self.freeze_authority.1)
        } else {
            None
        }
    }
}

unsafe impl Transmutable for Mint {
    /// The length of the `Mint` account data.
    const LEN: usize = core::mem::size_of::<Mint>();
}

impl Initializable for Mint {
    #[inline(always)]
    fn is_initialized(&self) -> Result<bool, ProgramError> {
        match self.is_initialized {
            0 => Ok(false),
            1 => Ok(true),
            _ => Err(ProgramError::InvalidAccountData),
        }
    }
}

// -- Instances below might be fully or partially autogenerated by macros in the future. --

// SAFETY: Token program accounts do not use a discriminator, relying on the account size and
// initialized field instead.  All account have different sizes.
unsafe impl AccountContent for Mint {
    const DISCRIMINATOR: &'static [u8] = &[];

    #[inline(always)]
    fn is_initialized(data: &[u8]) -> Result<bool, ProgramError> {
        let Some(is_initialized) = data.get(offset_of!(Mint, is_initialized)) else {
            return Err(ProgramError::InvalidAccountData);
        };

        match is_initialized {
            0 => Ok(false),
            1 => Ok(true),
            _ => Err(ProgramError::InvalidAccountData),
        }
    }

    #[inline(always)]
    unsafe fn is_of_type(data: &[u8]) -> bool {
        // `data` has already been checked by `is_initialized()`, so we only need to check the size
        // here.
        data.len() == size_of::<Self>()
    }

    type AsContent<'data> = &'data Self;

    #[inline(always)]
    unsafe fn content<'data>(data: &'data [u8]) -> Self::AsContent<'data> {
        // SAFETY: `Mint` is `#[repr(C)]` and can be constructed from its bytes.
        unsafe { &*data.as_ptr().cast::<Self>() }
    }

    type AsContentMut<'data> = &'data mut Self;

    #[inline(always)]
    unsafe fn content_mut<'data>(data: &'data mut [u8]) -> Self::AsContentMut<'data> {
        // SAFETY: `Mint` is `#[repr(C)]` and can be constructed from its bytes.
        unsafe { &mut *data.as_mut_ptr().cast::<Self>() }
    }
}

pub struct MintInit<'init> {
    pub mint_authority: &'init Pubkey,
    pub decimals: u8,
    pub freeze_authority: Option<&'init Pubkey>,
}

impl PInitializable for Mint {
    type Init<'init> = MintInit<'init>;

    #[inline(always)]
    unsafe fn initialize_bytes(
        state: MintInit<'_>,
        data: &mut [MaybeUninit<u8>],
    ) -> Result<(), ProgramError> {
        initialize_bytes_with_sized_self::<Self, _>(
            state,
            data,
            |MintInit {
                 mint_authority,
                 decimals,
                 freeze_authority,
             }: MintInit,
             uninit| {
                let ptr = uninit.as_mut_ptr();
                // SAFETY `uninit` is zero initialized, as required by `initialize_bytes()`.
                unsafe { set_coption_some(addr_of_mut!((*ptr).mint_authority), *mint_authority) };

                // All zeros is a valid bit pattern for `supply`.

                // SAFETY We are only writing though the potentially uninitialized pointer.
                unsafe { addr_of_mut!((*ptr).decimals).write(decimals) };

                // SAFETY We are only writing though the potentially uninitialized pointer.
                unsafe { addr_of_mut!((*ptr).is_initialized).write(1) };

                // SAFETY `uninit` is zero initialized, as required by `initialize_bytes()`.
                unsafe {
                    set_coption(
                        addr_of_mut!((*ptr).freeze_authority),
                        freeze_authority.map(|v| *v),
                    )
                };

                // SAFETY All fields that do not accept zero bit pattern as a valid state have been
                // initialized.
                unsafe { Ok(uninit.assume_init_mut()) }
            },
        )
    }
}
