use {
    super::{Initializable, Transmutable},
    crate::error::TokenError,
    core::{
        mem::{offset_of, MaybeUninit},
        ptr::addr_of_mut,
    },
    pinocchio::{
        account::{
            initialize_bytes_with_sized_self, AccountContent, Initializable as PInitializable,
        },
        program_error::ProgramError,
        pubkey::Pubkey,
    },
};

/// Minimum number of multisignature signers (min N)
pub const MIN_SIGNERS: u8 = 1;

/// Maximum number of multisignature signers (max N)
pub const MAX_SIGNERS: u8 = 11;

/// Multisignature data.
#[repr(C)]
pub struct Multisig {
    /// Number of signers required.
    pub m: u8,

    /// Number of valid signers.
    pub n: u8,

    /// Is `true` if this structure has been initialized.
    is_initialized: u8,

    /// Signer public keys.
    pub signers: [Pubkey; MAX_SIGNERS as usize],
}

impl Multisig {
    /// Utility function that checks index is between [`MIN_SIGNERS`] and
    /// [`MAX_SIGNERS`].
    #[inline(always)]
    pub fn is_valid_signer_index(index: u8) -> bool {
        (MIN_SIGNERS..=MAX_SIGNERS).contains(&index)
    }

    #[inline(always)]
    pub fn set_initialized(&mut self, value: bool) {
        self.is_initialized = value as u8;
    }
}

unsafe impl Transmutable for Multisig {
    /// The length of the `Multisig` account data.
    const LEN: usize = core::mem::size_of::<Multisig>();
}

impl Initializable for Multisig {
    #[inline(always)]
    fn is_initialized(&self) -> Result<bool, ProgramError> {
        match self.is_initialized {
            0 => Ok(false),
            1 => Ok(true),
            _ => Err(ProgramError::InvalidAccountData),
        }
    }
}

pub struct MultisigInit<'signers> {
    pub m: u8,
    pub signers: &'signers [Pubkey],
}

impl PInitializable for Multisig {
    type Init<'signers> = MultisigInit<'signers>;

    #[inline(always)]
    unsafe fn initialize_bytes(
        state: MultisigInit<'_>,
        data: &mut [MaybeUninit<u8>],
    ) -> Result<(), ProgramError> {
        initialize_bytes_with_sized_self::<Self, _>(
            state,
            data,
            |MultisigInit { m, signers }: MultisigInit, uninit| {
                if !Self::is_valid_signer_index(m) {
                    return Err(TokenError::InvalidNumberOfRequiredSigners.into());
                }
                let n = signers.len() as u8;
                if !Self::is_valid_signer_index(n) {
                    return Err(TokenError::InvalidNumberOfProvidedSigners.into());
                }

                let ptr = uninit.as_mut_ptr();
                // SAFETY We are only writing though the potentially uninitialized pointer.
                unsafe { addr_of_mut!((*ptr).m).write(m) };
                // SAFETY We are only writing though the potentially uninitialized pointer.
                unsafe { addr_of_mut!((*ptr).n).write(n) };
                // SAFETY We are only writing though the potentially uninitialized pointer.
                unsafe { addr_of_mut!((*ptr).is_initialized).write(1) };

                // `signers` holds
                let signers_dst = unsafe { &mut *addr_of_mut!((*ptr).signers) };
                for (dst, src) in signers_dst.iter_mut().zip(signers) {
                    *dst = *src;
                }

                // SAFETY All fields that do not accept zero bit pattern as a valid state have been
                // initialized.
                unsafe { Ok(uninit.assume_init_mut()) }
            },
        )
    }
}

// -- Instances below might be fully or partially autogenerated by macros in the future. --

// SAFETY: Token program accounts do not use a discriminator, relying on the account size and
// initialized field instead.  All account have different sizes.
unsafe impl AccountContent for Multisig {
    const DISCRIMINATOR: &'static [u8] = &[];

    #[inline(always)]
    fn is_initialized(data: &[u8]) -> Result<bool, ProgramError> {
        let Some(is_initialized) = data.get(offset_of!(Multisig, is_initialized)) else {
            return Err(ProgramError::InvalidAccountData);
        };

        match is_initialized {
            0 => Ok(false),
            1 => Ok(true),
            _ => Err(ProgramError::InvalidAccountData),
        }
    }

    #[inline(always)]
    unsafe fn is_of_type(data: &[u8]) -> bool {
        // `data` has already been checked by `is_initialized()`, so we only need to check the size
        // here.
        data.len() == size_of::<Self>()
    }

    type AsContent<'data> = &'data Self;

    #[inline(always)]
    unsafe fn content<'data>(data: &'data [u8]) -> Self::AsContent<'data> {
        // SAFETY: `Multisig` is `#[repr(C)]` and can be constructed from its bytes.
        unsafe { &*data.as_ptr().cast::<Self>() }
    }

    type AsContentMut<'data> = &'data mut Self;

    #[inline(always)]
    unsafe fn content_mut<'data>(data: &'data mut [u8]) -> Self::AsContentMut<'data> {
        // SAFETY: `Multisig` is `#[repr(C)]` and can be constructed from its bytes.
        unsafe { &mut *data.as_mut_ptr().cast::<Self>() }
    }
}
